export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: string;
  priceCents: number;
  category: MenuCategoryId;
  imageAlt: string;
  popular?: boolean;
  note?: string;
}

export type MenuCategoryId =
  | 'barbeque'
  | 'dinners'
  | 'deals'
  | 'meal-deals'
  | 'daily-specials'
  | 'sides'
  | 'desserts'
  | 'drinks';

export interface MenuSection {
  id: MenuCategoryId;
  label: string;
  description: string;
  hasSides?: boolean;
  items: MenuItem[];
}

export const menuSections: MenuSection[] = [
  {
    id: 'barbeque',
    label: 'Barbeque',
    description: 'All BBQ plates come with two sides of your choice and cornbread.',
    hasSides: true,
    items: [
      {
        id: 'rib-tips',
        name: 'Rib Tips',
        description: 'Tender, slow-smoked rib tips with Chef Daddy\'s signature BBQ seasoning.',
        price: '$16.00',
        priceCents: 1600,
        category: 'barbeque',
        imageAlt: 'BBQ rib tips at Chef Daddy\'s Bar-B-Que St. Louis',
        popular: true,
      },
      {
        id: 'pork-rib-slabs',
        name: 'Pork Rib Slabs (3 Bones)',
        description: 'Three bones of slow-smoked St. Louis-style pork ribs, seasoned and smoked to perfection.',
        price: '$16.00',
        priceCents: 1600,
        category: 'barbeque',
        imageAlt: 'Pork rib slabs at Chef Daddy\'s BBQ St. Louis',
        popular: true,
      },
      {
        id: 'beef-back-ribs',
        name: 'Beef Back Ribs (2 Bones)',
        description: 'Two meaty beef back ribs smoked low and slow until fall-off-the-bone tender.',
        price: '$16.00',
        priceCents: 1600,
        category: 'barbeque',
        imageAlt: 'Beef back ribs at Chef Daddy\'s Bar-B-Que',
      },
      {
        id: 'bbq-porksteak',
        name: 'BBQ Porksteak',
        description: 'A hearty porksteak seasoned and smoked with Chef Daddy\'s BBQ rub.',
        price: '$15.00',
        priceCents: 1500,
        category: 'barbeque',
        imageAlt: 'BBQ porksteak at Chef Daddy\'s St. Louis',
        popular: true,
      },
      {
        id: 'turkey-tips',
        name: 'Turkey Tips',
        description: 'Smoked turkey tips — a flavorful, lighter BBQ option that\'s anything but ordinary.',
        price: '$17.00',
        priceCents: 1700,
        category: 'barbeque',
        imageAlt: 'Smoked turkey tips at Chef Daddy\'s BBQ',
      },
      {
        id: 'half-chicken',
        name: 'Half Chicken',
        description: 'A full half chicken smoked to juicy perfection with a crisp, seasoned exterior.',
        price: '$16.50',
        priceCents: 1650,
        category: 'barbeque',
        imageAlt: 'BBQ half chicken at Chef Daddy\'s Bar-B-Que St. Louis',
      },
    ],
  },
  {
    id: 'dinners',
    label: 'Dinners',
    description: 'All dinners come with two sides of your choice and cornbread.',
    hasSides: true,
    items: [
      {
        id: 'smothered-porkchops',
        name: 'Smothered Porkchops',
        description: 'Tender porkchops slow-cooked and smothered in a rich, savory gravy.',
        price: '$20.00',
        priceCents: 2000,
        category: 'dinners',
        imageAlt: 'Smothered porkchops dinner at Chef Daddy\'s Soul Food St. Louis',
        popular: true,
      },
      {
        id: 'fried-catfish-fillets',
        name: 'Fried Catfish Fillets',
        description: 'Golden-fried catfish fillets with a perfectly seasoned crispy crust.',
        price: '$15.00',
        priceCents: 1500,
        category: 'dinners',
        imageAlt: 'Fried catfish fillets dinner at Chef Daddy\'s',
        popular: true,
      },
      {
        id: 'fried-wings',
        name: '4pc Fried Wings',
        description: 'Four crispy, golden-fried wings seasoned with Chef Daddy\'s house blend.',
        price: '$15.00',
        priceCents: 1500,
        category: 'dinners',
        imageAlt: '4 piece fried wings at Chef Daddy\'s Soul Food',
      },
      {
        id: 'smothered-chicken',
        name: 'Smothered Chicken',
        description: 'Juicy chicken pieces slow-cooked and smothered in homemade gravy.',
        price: '$15.00',
        priceCents: 1500,
        category: 'dinners',
        imageAlt: 'Smothered chicken dinner at Chef Daddy\'s St. Louis',
      },
      {
        id: 'neckbones-potatoes',
        name: 'Neckbones & Potatoes',
        description: 'Slow-cooked pork neckbones and tender potatoes — classic soul food comfort.',
        price: '$15.00',
        priceCents: 1500,
        category: 'dinners',
        imageAlt: 'Neckbones and potatoes at Chef Daddy\'s Soul Food',
      },
      {
        id: 'pork-steak',
        name: 'Pork Steak',
        description: 'A seasoned pork steak cooked to tender, juicy perfection.',
        price: '$15.00',
        priceCents: 1500,
        category: 'dinners',
        imageAlt: 'Pork steak dinner at Chef Daddy\'s Bar-B-Que',
      },
      {
        id: 'hamhocks',
        name: 'Hamhocks',
        description: 'Slow-cooked hamhocks fall-off-the-bone tender with deep, smoky flavor.',
        price: '$20.00',
        priceCents: 2000,
        category: 'dinners',
        imageAlt: 'Hamhocks soul food dinner at Chef Daddy\'s St. Louis',
      },
      {
        id: 'chitterlings',
        name: 'Chitterlings',
        description: 'Cleaned and slow-cooked chitterlings prepared the authentic Southern way.',
        price: '$30.00',
        priceCents: 3000,
        category: 'dinners',
        imageAlt: 'Chitterlings soul food at Chef Daddy\'s St. Louis',
        note: 'Available Fridays — call ahead to confirm availability',
      },
      {
        id: 'fried-porkchop',
        name: '2pc Fried Porkchop',
        description: 'Two thick-cut porkchops, seasoned and fried to a golden crisp.',
        price: '$20.00',
        priceCents: 2000,
        category: 'dinners',
        imageAlt: 'Fried porkchop dinner at Chef Daddy\'s Soul Food',
      },
    ],
  },
  {
    id: 'deals',
    label: '$4.99 Deals',
    description: 'Great food at an unbeatable price. Each deal comes with two sides and cornbread.',
    hasSides: true,
    items: [
      {
        id: 'deal-baked-chicken',
        name: 'Baked Chicken',
        description: 'Oven-baked chicken seasoned with Chef Daddy\'s house blend. A classic done right.',
        price: '$4.99',
        priceCents: 499,
        category: 'deals',
        imageAlt: 'Baked chicken $4.99 deal at Chef Daddy\'s St. Louis',
        popular: true,
      },
      {
        id: 'deal-meatloaf',
        name: 'Meatloaf',
        description: 'Homestyle meatloaf made from scratch — hearty, filling, and full of flavor.',
        price: '$4.99',
        priceCents: 499,
        category: 'deals',
        imageAlt: 'Meatloaf $4.99 deal at Chef Daddy\'s Soul Food',
      },
      {
        id: 'deal-fried-porkchop',
        name: 'Fried Porkchop',
        description: 'A golden-fried porkchop seasoned and cooked to perfection at an unbeatable price.',
        price: '$4.99',
        priceCents: 499,
        category: 'deals',
        imageAlt: 'Fried porkchop $4.99 deal at Chef Daddy\'s',
      },
    ],
  },
  {
    id: 'meal-deals',
    label: '$9.99 Meal Deals',
    description: 'A full meal at a great value. Each deal comes with two sides and cornbread.',
    hasSides: true,
    items: [
      {
        id: 'meal-baked-chicken',
        name: 'Baked Chicken',
        description: 'Oven-baked chicken seasoned with Chef Daddy\'s house blend. A classic done right.',
        price: '$9.99',
        priceCents: 999,
        category: 'meal-deals',
        imageAlt: 'Baked chicken $9.99 meal deal at Chef Daddy\'s St. Louis',
        popular: true,
      },
      {
        id: 'meal-meatloaf',
        name: 'Meatloaf',
        description: 'Homestyle meatloaf made from scratch — hearty, filling, and full of flavor.',
        price: '$9.99',
        priceCents: 999,
        category: 'meal-deals',
        imageAlt: 'Meatloaf $9.99 meal deal at Chef Daddy\'s Soul Food',
      },
      {
        id: 'meal-fried-porkchop',
        name: 'Fried Porkchop',
        description: 'A golden-fried porkchop seasoned and cooked to perfection.',
        price: '$9.99',
        priceCents: 999,
        category: 'meal-deals',
        imageAlt: 'Fried porkchop $9.99 meal deal at Chef Daddy\'s',
      },
    ],
  },
  {
    id: 'daily-specials',
    label: 'Daily Specials',
    description: 'Fresh specials every day of the week. All meals come with two sides and cornbread.',
    hasSides: true,
    items: [
      {
        id: 'special-tuesday',
        name: 'Tuesday — Pot Roast & Mixed Veggies',
        description: 'Slow-cooked pot roast with mixed vegetables. Tender, rich, and satisfying.',
        price: '$15.00',
        priceCents: 1500,
        category: 'daily-specials',
        imageAlt: 'Tuesday pot roast special at Chef Daddy\'s St. Louis',
        note: 'Available Tuesdays only',
      },
      {
        id: 'special-wednesday',
        name: 'Wednesday — Turkey Leg',
        description: 'A massive, fall-off-the-bone smoked turkey leg. Wednesday\'s crowd favorite.',
        price: '$20.00',
        priceCents: 2000,
        category: 'daily-specials',
        imageAlt: 'Wednesday turkey leg special at Chef Daddy\'s',
        note: 'Available Wednesdays only',
        popular: true,
      },
      {
        id: 'special-thursday',
        name: 'Thursday — Smothered OxTails',
        description: 'Braised oxtails slow-cooked until melt-in-your-mouth tender and smothered in rich gravy.',
        price: '$25.00',
        priceCents: 2500,
        category: 'daily-specials',
        imageAlt: 'Thursday smothered oxtails special at Chef Daddy\'s Soul Food',
        note: 'Available Thursdays only',
        popular: true,
      },
      {
        id: 'special-friday',
        name: 'Friday — Fish, Spaghetti, & Slaw',
        description: 'Fried fish served with spaghetti and coleslaw — a St. Louis Friday tradition.',
        price: '$15.00',
        priceCents: 1500,
        category: 'daily-specials',
        imageAlt: 'Friday fish spaghetti and slaw special at Chef Daddy\'s',
        note: 'Available Fridays only',
        popular: true,
      },
      {
        id: 'special-saturday',
        name: 'Saturday — Chef\'s Special',
        description: 'Chef Daddy\'s personal creation of the week. Ask your server or call ahead to find out what\'s cooking.',
        price: 'Ask Us',
        priceCents: 0,
        category: 'daily-specials',
        imageAlt: 'Saturday chef\'s special at Chef Daddy\'s Bar-B-Que St. Louis',
        note: 'Available Saturdays only — price varies',
      },
    ],
  },
  {
    id: 'sides',
    label: 'Sides',
    description: 'Small $3.50 · Large $5.00 — Made fresh daily.',
    items: [
      {
        id: 'side-green-beans',
        name: 'Green Beans',
        description: 'Slow-cooked Southern-style green beans.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Green beans side at Chef Daddy\'s Soul Food',
      },
      {
        id: 'side-corn',
        name: 'Corn',
        description: 'Sweet, buttery corn cooked just right.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Corn side at Chef Daddy\'s',
      },
      {
        id: 'side-mashed-potatoes',
        name: 'Mashed Potatoes',
        description: 'Creamy, buttery homestyle mashed potatoes.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Mashed potatoes side at Chef Daddy\'s St. Louis',
      },
      {
        id: 'side-black-eyed-peas',
        name: 'Black Eyed Peas',
        description: 'Slow-cooked black eyed peas seasoned Southern-style.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Black eyed peas side at Chef Daddy\'s Soul Food',
      },
      {
        id: 'side-northern-white-beans',
        name: 'Northern White Beans',
        description: 'Tender white beans slow-cooked with savory seasoning.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Northern white beans side at Chef Daddy\'s',
      },
      {
        id: 'side-peas-butter-beans',
        name: 'Peas & Butter Beans',
        description: 'A Southern classic — peas and butter beans cooked low and slow.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Peas and butter beans side at Chef Daddy\'s St. Louis',
      },
      {
        id: 'side-rice',
        name: 'Rice',
        description: 'Fluffy, perfectly cooked white rice.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Rice side at Chef Daddy\'s Bar-B-Que',
      },
      {
        id: 'side-cabbage',
        name: 'Cabbage',
        description: 'Slow-cooked seasoned cabbage the Southern way.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Cabbage side at Chef Daddy\'s Soul Food',
      },
      {
        id: 'side-mississippi-greens',
        name: 'Mississippi Greens',
        description: 'Hearty greens slow-cooked with rich seasoning — deep Southern flavor.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Mississippi greens side at Chef Daddy\'s',
        popular: true,
      },
      {
        id: 'side-sweet-potatoes',
        name: 'Sweet Potatoes',
        description: 'Candied sweet potatoes cooked until tender and perfectly sweetened.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Sweet potatoes side at Chef Daddy\'s Soul Food St. Louis',
      },
      {
        id: 'side-mac-cheese',
        name: 'Baked Mac & Cheese',
        description: 'Rich, creamy, and baked to a golden finish. Made from scratch with a blend of real cheeses — comfort food at its finest.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Baked mac and cheese side at Chef Daddy\'s St. Louis',
        popular: true,
      },
      {
        id: 'side-potato-salad',
        name: 'Potato Salad',
        description: 'Creamy Southern-style potato salad made fresh.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Potato salad side at Chef Daddy\'s Bar-B-Que',
      },
      {
        id: 'side-coleslaw',
        name: 'Coleslaw',
        description: 'Cool, creamy coleslaw — the perfect complement to smoky BBQ.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Coleslaw side at Chef Daddy\'s BBQ St. Louis',
      },
      {
        id: 'side-okra',
        name: 'Okra',
        description: 'Seasoned okra cooked Southern-style.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Okra side at Chef Daddy\'s Soul Food',
      },
      {
        id: 'side-dressing',
        name: 'Dressing',
        description: 'House-made Southern cornbread dressing.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Southern dressing side at Chef Daddy\'s',
        note: 'Sundays only',
      },
      {
        id: 'side-spaghetti',
        name: 'Spaghetti',
        description: 'Homestyle spaghetti with savory meat sauce.',
        price: 'Sm $3.50 / Lg $5.00',
        priceCents: 350,
        category: 'sides',
        imageAlt: 'Spaghetti side at Chef Daddy\'s St. Louis',
        note: 'Fridays only',
      },
    ],
  },
  {
    id: 'desserts',
    label: 'Desserts',
    description: 'All desserts $5.00. Save room — you\'re going to want to.',
    items: [
      {
        id: 'peach-cobbler',
        name: 'Peach Cobbler',
        description: 'Warm, homemade peach cobbler with a buttery golden crust.',
        price: '$5.00',
        priceCents: 500,
        category: 'desserts',
        imageAlt: 'Homemade peach cobbler at Chef Daddy\'s Soul Food St. Louis',
        popular: true,
      },
      {
        id: 'banana-pudding',
        name: 'Banana Pudding',
        description: 'Creamy, layered banana pudding made the old-school Southern way.',
        price: '$5.00',
        priceCents: 500,
        category: 'desserts',
        imageAlt: 'Banana pudding dessert at Chef Daddy\'s',
        popular: true,
      },
      {
        id: 'caramel-cake',
        name: 'Caramel Cake',
        description: 'Rich, moist cake layered with smooth homemade caramel icing.',
        price: '$5.00',
        priceCents: 500,
        category: 'desserts',
        imageAlt: 'Caramel cake dessert at Chef Daddy\'s Soul Food',
      },
      {
        id: 'banana-pudding-cake',
        name: 'Banana Pudding Cake',
        description: 'All the flavors of banana pudding baked into a decadent slice of cake.',
        price: '$5.00',
        priceCents: 500,
        category: 'desserts',
        imageAlt: 'Banana pudding cake at Chef Daddy\'s St. Louis',
      },
      {
        id: 'double-chocolate-cake',
        name: 'Double Chocolate Cake',
        description: 'Rich, moist double chocolate cake — for the chocolate lover in the group.',
        price: '$5.00',
        priceCents: 500,
        category: 'desserts',
        imageAlt: 'Double chocolate cake at Chef Daddy\'s Bar-B-Que',
      },
      {
        id: 'carrot-cake',
        name: 'Carrot Cake',
        description: 'Spiced carrot cake with a creamy frosting — a classic Southern dessert.',
        price: '$5.00',
        priceCents: 500,
        category: 'desserts',
        imageAlt: 'Carrot cake dessert at Chef Daddy\'s Soul Food St. Louis',
      },
    ],
  },
  {
    id: 'drinks',
    label: 'Drinks',
    description: 'All drinks $1.99.',
    items: [
      {
        id: 'drink-fountain',
        name: 'Fountain Drinks',
        description: 'Your choice of fountain soda.',
        price: '$1.99',
        priceCents: 199,
        category: 'drinks',
        imageAlt: 'Fountain drinks at Chef Daddy\'s Bar-B-Que',
      },
      {
        id: 'drink-canned-soda',
        name: 'Assorted Canned Soda',
        description: 'Assorted canned sodas — ask your server for available options.',
        price: '$1.99',
        priceCents: 199,
        category: 'drinks',
        imageAlt: 'Canned soda at Chef Daddy\'s St. Louis',
      },
      {
        id: 'drink-kool-aid',
        name: 'Kool-Aid',
        description: 'Classic Kool-Aid — cold and refreshing.',
        price: '$1.99',
        priceCents: 199,
        category: 'drinks',
        imageAlt: 'Kool-Aid at Chef Daddy\'s Soul Food',
      },
      {
        id: 'drink-iced-tea',
        name: 'Iced Tea',
        description: 'Cold, refreshing iced tea.',
        price: '$1.99',
        priceCents: 199,
        category: 'drinks',
        imageAlt: 'Iced tea at Chef Daddy\'s Bar-B-Que St. Louis',
      },
    ],
  },
];

export const popularItems = menuSections
  .flatMap((s) => s.items)
  .filter((i) => i.popular);
